[tool.poetry]
name = "portability"
version = "0.1.0"
description = ""
authors = ["frasermince"]

[tool.poetry.dependencies]
python = "^3.9"
datasets = "^2.4.0"
tqdm = "^4.64.0"
code-tokenize = "^0.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
